# Generated by Django 5.1.4 on 2025-01-17 09:25

import meiduo.utils.fastdfs.fdfs_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(storage=meiduo.utils.fastdfs.fdfs_storage.FastDFSStorage, upload_to='', verbose_name='Logo图片'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='default_image_url',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, storage=meiduo.utils.fastdfs.fdfs_storage.FastDFSStorage(), upload_to='', verbose_name='默认图片'),
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='image',
            field=models.ImageField(storage=meiduo.utils.fastdfs.fdfs_storage.FastDFSStorage(), upload_to='', verbose_name='图片'),
        ),
    ]
