# Generated by Django 5.1.4 on 2025-01-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_brand_logo_alter_sku_default_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='default_image_url',
            new_name='default_image',
        ),
    ]
