# Generated by Django 5.1.4 on 2025-01-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goodsvisitcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsVisitCount',
        ),
    ]
