# Generated by Django 5.1.4 on 2025-01-17 09:21

import meiduo.utils.fastdfs.fdfs_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=meiduo.utils.fastdfs.fdfs_storage.FastDFSStorage, upload_to='', verbose_name='图片'),
        ),
    ]
